# Generated by Django 6.0.5 on 2026-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('iPad', 'iPad'), ('Mac', 'Mac'), ('Watch', 'Watch'), ('AirPods', 'AirPods'), ('Accessories', 'Accessories'), ('Vision', 'Vision')], max_length=50),
        ),
    ]
