# Generated by Django 6.0.5 on 2026-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('iPad', 'iPad'), ('Mac', 'Mac'), ('Watch', 'Watch'), ('AirPods', 'AirPods'), ('Accessories', 'Accessories'), ('Vision', 'Vision')], default='iPhone', max_length=50),
        ),
    ]
