# Generated by Django 6.0.5 on 2026-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),

        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                max_length=20,
                default='Pending'
            ),
        ),

        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2
            ),
        ),

        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2
            ),
        ),

        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(
                max_length=200
            ),
        ),

        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(
                default=1
            ),
        ),
    ]